<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Autentificación</title>
    <link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css">
</head>

<body>
    <h2>Acceso restringido</h2>
    <p>Esta p&#225;gina tiene restringido el acceso</p>
    <form style="margin:12px;" name="password" method="post" action="?view=main">
        <legend> Inserte la contraseña</legend>
        <input type="password" name="password">
        <input type="submit" name="Submit" value="Aceptar" class="primary">
    </form>
</body>

</html>